# -*- coding: utf-8 -*-
"""password_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOfBMzOa9WDO_BTSDghGZXBhF70gGXI5
"""



common_pass=['password',"12345678","pass1234"]
def strength(score):
    match score:
        case _ if 0<= score <=5:
              print("weak")
        case _ if 6<= score <=10:
              print("medium")
        case _ if 11<= score <=15:
              print("strong")
pas=input()
sp_char=['~','!','@','#','$','^','%','&','*']
a=[0]*6
a[5]=2
score=0
f=["❌ length is less than 8",
"❌ no capital letter",
"❌ no lower case letter",
"❌ no number" ,
"❌ no special character",
"❌ space is prohibited"]
if len(pas)>=8:a[0]=2
for x in pas:
  if 'A'<=x<='Z':
      a[1]=2
  if 'a'<=x<='z':
      a[2]=1
  if '0'<=x<='9':
       a[3]=3
  if   x in sp_char:
         a[4]=5
  if x==' ':
         a[5]=0
for i in range(6):
  score+=a[i]
print(f"score of your password : {score} out of 15 ")
strength(score)
print("feedback :")
for i in range(6):
  if(a[i]<=0):print(f[i])
if pas not in common_pass:print("good😃 your password is not that common")
else :print("❌ your password is that common")

